web: &web
  url:
    login: http://127.0.0.1
  key: xy-token

iam: &iam
  key: xy-auth
  url: http://127.0.0.1:3399
  uri:
    auth: /iam/auth
  project_name: tools-english
  project_auth_code: "*t-o-o-l-s*"

flask: &flask
  host: 0.0.0.0
  port: 3301
  threaded: true
  debug: true

flask-config: &flask-config
  SECRET_KEY: tools
  PERMANENT_SESSION_LIFETIME:
    days: 30

database: &database
  english:
    scheme: mysql+pymysql
    user: root
    password: 123456
    host: 127.0.0.1
    port: 3306
    db: tools_english
    charset: utf8mb4

cache: &cache
  serialize: pickle
  redis: &redis
    password: null
    host: 127.0.0.1
    port: 6379
    db: 0
    ex: 86400

ssl: &ssl
  private_key: 2_ray3175.cn.key
  public_key: 1_ray3175.cn_bundle.crt


environment-product:
  web:
    <<: *web
  iam:
    <<: *iam
  flask:
    debug: false
    <<: *flask
  flask-config:
    SECRET_KEY: tools-english
    <<: *flask-config
  database:
    <<: *database
  cache:
    redis:
      password: null
      host: 127.0.0.1
      port: 6379
      <<: *redis
    <<: *cache
  ssl:
    <<: *ssl

environment-development:
  web:
    <<: *web
  iam:
    <<: *iam
  flask:
    <<: *flask
  flask-config:
    <<: *flask-config
  database:
    <<: *database
  cache:
    <<: *cache
  ssl:
    <<: *ssl

environment-test:
  web:
    <<: *web
  iam:
    <<: *iam
  flask:
    debug: false
    <<: *flask
  flask-config:
    <<: *flask-config
  database:
    <<: *database
  cache:
    redis:
      host: 127.0.0.1
      port: 6379
      <<: *redis
    <<: *cache
  ssl:
    <<: *ssl

